apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiscal
  namespace: production
  labels:
    app: fiscal
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  selector:
    matchLabels:
      app: fiscal
  template:
    metadata:
      namespace: production
      labels:
        app: fiscal
    spec:
      containers:
      - name: fiscal
        image: cr.yandex/crpfb8t478v3of681kce/fiscal:1.0.24
        imagePullPolicy: Always
        ports:
          - containerPort: 5500
        readinessProbe:
          httpGet:
            path: /health
            port: 5500
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: fiscal-config
      imagePullSecrets:
      - name: gitlabregistrycred
